# Generated by Django 4.0.4 on 2022-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('type', models.CharField(choices=[('restaurant', 'Ресторан'), ('worker', 'Курьер'), ('company', 'Компания')], max_length=100, verbose_name='Тип')),
                ('contact', models.CharField(max_length=256, verbose_name='Способ связи')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
