# Generated by Django 4.0.4 on 2022-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
