# Generated by Django 4.0.4 on 2022-04-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='phones',
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='phone',
            new_name='phones',
        ),
    ]
