# Generated by Django 4.0.4 on 2022-04-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
        ('company', '0002_rename_phone_company_phones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpers.location'),
            preserve_default=False,
        ),
    ]
