# Generated by Django 4.0.2 on 2022-05-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='album',
            field=models.ManyToManyField(blank=True, to='menu.MealAlbum', verbose_name='Альбом фотографий'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(blank=True, to='menu.Category', verbose_name='Категории'),
        ),
    ]
