# Generated by Django 4.0.4 on 2022-04-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_name_alter_restaurantaddress_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_meal_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantaddress', verbose_name='Адресс доставки'),
            preserve_default=False,
        ),
    ]
