# Generated by Django 4.0.4 on 2022-05-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_alter_meal_album_alter_meal_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('delivery_date', models.DateField(verbose_name='Дата заказа')),
                ('time_delivery', models.CharField(choices=[('9:00', '9:00'), ('12:00', '12:00'), ('15:00', '15:00')], max_length=5, verbose_name='Время доставки')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Способ связи')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Адрес')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Описание')),
                ('meals', models.ManyToManyField(to='menu.meal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
