# Generated by Django 4.0.4 on 2022-05-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
