# Generated by Django 4.0.4 on 2022-04-18 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_comments_user_meal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='photos',
        ),
        migrations.AddField(
            model_name='mealphoto',
            name='photos',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.meal', verbose_name='Альбом'),
            preserve_default=False,
        ),
    ]
