# Generated by Django 4.0.4 on 2022-05-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
