# Generated by Django 4.0.4 on 2022-04-20 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0005_mealphoto_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='menu/meals/', verbose_name='Фото')),
                ('main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MealPhoto',
        ),
        migrations.AddField(
            model_name='meal',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='menu.mealalbum', verbose_name='Альбом фотографий'),
        ),
    ]
