# Generated by Django 4.0.4 on 2022-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание'),
        ),
    ]
